name = "r2-registry"

workers_dev = false
main = "./index.ts"
compatibility_date = "2024-06-18"
compatibility_flags = []
routes = ["registry.uuid.rocks/*"]

r2_buckets = [{ binding = "REGISTRY", bucket_name = "r2-registry" }]

[vars]
JWT_REGISTRY_TOKENS_PUBLIC_KEY = "eyJrdHkiOiJFQyIsImtleV9vcHMiOlsidmVyaWZ5Il0sImV4dCI6dHJ1ZSwiY3J2IjoiUC0yNTYiLCJ4IjoiZmMxMUdDVHpKU3BfWWtBV3lvQ0lUWHRHY01FaE9PNURRWERjdTlxNmtNUSIsInkiOiJNQjNmUjRyY2lrcWlKc0c2MHBfSHFRcGVjNHhNSUN2dThIWWJ1RjItZnE4In0="
USERNAME = "jh"
# PASSWORD= <in secrets>

# Secrets:
# USERNAME/PASSWORD if you want username/password based auth


## Dev - For local dev using `wrangler dev`
[env.dev]
r2_buckets = [{ binding = "REGISTRY", bucket_name = "r2-image-registry-dev" }]
[env.dev.vars]
# REGISTRIES_JSON = "[{ \"registry\": \"http://localhost:9999\", \"password_env\": \"PASSWORD\", \"username\": \"hello\" }]"
USERNAME = "hello"
PASSWORD = "world"
# The necessary secrets are:
# Setup those secrets on .dev.vars in the root of the project
#
